version: '3'
services:
  postgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_DB=blog-project
      - POSTGRES_USER=jun-admin
      - POSTGRES_PASSWORD=DevAdmin
  nginx:
    restart: unless-stopped
    build:
      dockerfile: dev.Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
      - '1337:1337'
  backend:
    build:
      dockerfile: dev.Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=blog-project
      - POSTGRES_USER=jun-admin
      - POSTGRES_PASSWORD=DevAdmin
  client:
    build:
      dockerfile: dev.Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
